package com.hanadulset.pro_poseapp.core.designsystem.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/** Generated By Plugin
 *
 * **/
internal val IconLogo: ImageVector
    get() {
        if (_iconLogo != null) {
            return _iconLogo!!
        }
        _iconLogo = Builder(
            name = "IconLogo", defaultWidth = 82.0.dp, defaultHeight = 82.0.dp,
            viewportWidth = 82.0f, viewportHeight = 82.0f
        ).apply {
            group {
                path(
                    fill = SolidColor(Color(0xFFF9F9FF)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero
                ) {
                    moveTo(7.1304f, 11.4087f)
                    horizontalLineToRelative(67.0261f)
                    verticalLineToRelative(67.7391f)
                    horizontalLineToRelative(-67.0261f)
                    close()
                }
                path(
                    fill = SolidColor(Color(0xFF191C20)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero
                ) {
                    moveTo(4.1961f, 22.4539f)
                    lineTo(4.2441f, 36.2754f)
                    lineTo(4.7727f, 36.3234f)
                    lineTo(5.2852f, 36.3715f)
                    verticalLineTo(58.5531f)
                    verticalLineTo(80.7188f)
                    horizontalLineTo(27.707f)
                    horizontalLineTo(50.1289f)
                    verticalLineTo(81.3594f)
                    verticalLineTo(82.0f)
                    horizontalLineTo(63.9824f)
                    horizontalLineTo(77.8359f)
                    verticalLineTo(68.2266f)
                    verticalLineTo(54.4531f)
                    horizontalLineTo(76.9551f)
                    horizontalLineTo(76.0742f)
                    verticalLineTo(32.1914f)
                    verticalLineTo(9.9297f)
                    horizontalLineTo(53.9727f)
                    horizontalLineTo(31.8711f)
                    verticalLineTo(9.2891f)
                    verticalLineTo(8.6484f)
                    horizontalLineTo(18.0176f)
                    horizontalLineTo(4.1641f)
                    lineTo(4.1961f, 22.4539f)
                    close()
                    moveTo(74.3125f, 33.0563f)
                    verticalLineTo(54.4371f)
                    lineTo(73.4797f, 54.4852f)
                    lineTo(72.6309f, 54.5332f)
                    lineTo(72.5828f, 65.7121f)
                    lineTo(72.5508f, 76.875f)
                    horizontalLineTo(61.3398f)
                    horizontalLineTo(50.1289f)
                    verticalLineTo(77.916f)
                    verticalLineTo(78.957f)
                    horizontalLineTo(28.5879f)
                    horizontalLineTo(7.0469f)
                    verticalLineTo(57.5602f)
                    verticalLineTo(36.1633f)
                    lineTo(8.248f, 36.2273f)
                    lineTo(9.4492f, 36.2754f)
                    verticalLineTo(25.0324f)
                    verticalLineTo(13.7734f)
                    horizontalLineTo(20.6602f)
                    horizontalLineTo(31.8711f)
                    verticalLineTo(12.7324f)
                    verticalLineTo(11.6914f)
                    horizontalLineTo(53.0918f)
                    horizontalLineTo(74.3125f)
                    verticalLineTo(33.0563f)
                    close()
                }
                path(
                    fill = SolidColor(Color(0xFF191C20)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero
                ) {
                    moveTo(40.119f, 23.1906f)
                    curveTo(38.7737f, 23.2386f, 35.6187f, 23.8152f, 33.9851f, 24.2796f)
                    curveTo(28.8761f, 25.7531f, 24.664f, 29.0203f, 21.8933f, 33.6007f)
                    curveTo(20.2757f, 36.2753f, 19.0265f, 39.9589f, 18.8023f, 42.7777f)
                    curveTo(18.7222f, 43.6105f, 18.6421f, 43.9949f, 18.546f, 43.8507f)
                    curveTo(18.4019f, 43.6425f, 18.4499f, 44.5554f, 18.7542f, 47.6464f)
                    curveTo(19.603f, 56.3749f, 25.1925f, 63.5339f, 33.2323f, 66.1925f)
                    curveTo(38.069f, 67.7941f, 43.146f, 67.8742f, 47.5663f, 66.4167f)
                    curveTo(55.1097f, 63.9343f, 60.2187f, 58.5531f, 61.9483f, 51.2499f)
                    curveTo(62.1566f, 50.321f, 62.3808f, 49.4562f, 62.4288f, 49.3281f)
                    curveTo(62.605f, 48.7835f, 62.653f, 43.9628f, 62.4769f, 42.7136f)
                    curveTo(61.9483f, 38.9179f, 60.6831f, 35.4906f, 58.6812f, 32.4796f)
                    curveTo(57.6882f, 31.0062f, 55.3179f, 28.5238f, 53.8444f, 27.4187f)
                    curveTo(50.9776f, 25.3046f, 47.214f, 23.8312f, 43.4823f, 23.3828f)
                    curveTo(41.4964f, 23.1585f, 41.2081f, 23.1265f, 40.119f, 23.1906f)
                    close()
                    moveTo(45.3401f, 28.0914f)
                    curveTo(50.337f, 29.3566f, 54.1327f, 32.3195f, 56.3589f, 36.6757f)
                    curveTo(57.7523f, 39.3984f, 58.3608f, 41.9289f, 58.3608f, 45.0039f)
                    curveTo(58.3448f, 47.3582f, 58.2487f, 48.9917f, 58.1046f, 48.9117f)
                    curveTo(58.0565f, 48.8796f, 57.9605f, 49.1519f, 57.8964f, 49.5203f)
                    curveTo(57.6401f, 51.0097f, 56.2788f, 54.1488f, 55.2058f, 55.7183f)
                    curveTo(53.1718f, 58.6972f, 50.0327f, 61.0996f, 46.7495f, 62.2367f)
                    curveTo(45.1159f, 62.7812f, 42.2171f, 63.2617f, 40.4394f, 63.2617f)
                    curveTo(37.0601f, 63.2617f, 32.6878f, 61.8523f, 29.8851f, 59.8343f)
                    curveTo(27.9632f, 58.457f, 25.9773f, 56.1027f, 24.8722f, 53.8925f)
                    curveTo(24.3276f, 52.8355f, 23.623f, 50.8015f, 23.4468f, 49.8566f)
                    curveTo(23.3827f, 49.5203f, 23.2866f, 49.1679f, 23.2226f, 49.0878f)
                    curveTo(23.1425f, 48.9917f, 23.1105f, 47.4863f, 23.1265f, 45.7246f)
                    curveTo(23.1585f, 42.8578f, 23.2065f, 42.3613f, 23.5749f, 40.9999f)
                    curveTo(25.4327f, 34.1132f, 30.4296f, 29.1484f, 36.6757f, 27.9632f)
                    curveTo(37.3964f, 27.8191f, 38.2612f, 27.707f, 38.6136f, 27.707f)
                    curveTo(38.9499f, 27.707f, 39.2542f, 27.6589f, 39.2862f, 27.5788f)
                    curveTo(39.4464f, 27.3226f, 43.7866f, 27.691f, 45.3401f, 28.0914f)
                    close()
                    moveTo(22.8542f, 46.7976f)
                    curveTo(22.8062f, 46.9097f, 22.7741f, 46.8296f, 22.7741f, 46.6054f)
                    curveTo(22.7741f, 46.3812f, 22.8062f, 46.3011f, 22.8542f, 46.3972f)
                    curveTo(22.8862f, 46.5093f, 22.8862f, 46.7015f, 22.8542f, 46.7976f)
                    close()
                }
                path(
                    fill = SolidColor(Color(0xFF191C20)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero
                ) {
                    moveTo(39.3185f, 31.9351f)
                    curveTo(35.6349f, 32.4636f, 32.2396f, 34.2734f, 30.2536f, 36.8039f)
                    curveTo(28.2517f, 39.3023f, 27.3228f, 42.105f, 27.3548f, 45.4843f)
                    curveTo(27.3708f, 47.8066f, 27.6911f, 49.248f, 28.588f, 51.2019f)
                    curveTo(31.7111f, 57.9605f, 40.3595f, 60.6832f, 47.2782f, 57.0636f)
                    curveTo(50.2091f, 55.5261f, 52.4032f, 52.8195f, 53.4923f, 49.4082f)
                    curveTo(53.9888f, 47.8386f, 54.1009f, 44.9398f, 53.7486f, 43.0339f)
                    curveTo(53.4603f, 41.4964f, 52.8196f, 39.6226f, 52.0829f, 38.1812f)
                    lineTo(51.6185f, 37.2683f)
                    lineTo(51.5384f, 38.2933f)
                    curveTo(51.2982f, 41.2882f, 48.7997f, 42.9859f, 46.3814f, 41.8167f)
                    curveTo(45.5806f, 41.4164f, 44.2513f, 40.055f, 44.1071f, 39.4625f)
                    curveTo(44.0591f, 39.2542f, 43.963f, 39.1101f, 43.8989f, 39.1421f)
                    curveTo(43.7228f, 39.2542f, 43.8029f, 37.5726f, 44.0111f, 36.964f)
                    curveTo(44.4595f, 35.6828f, 46.5255f, 34.3214f, 47.8228f, 34.4816f)
                    curveTo(48.2071f, 34.5136f, 48.5275f, 34.4976f, 48.5275f, 34.4175f)
                    curveTo(48.5275f, 34.3375f, 48.4314f, 34.2734f, 48.3193f, 34.2734f)
                    curveTo(48.1911f, 34.2734f, 47.9349f, 34.0972f, 47.7427f, 33.889f)
                    curveTo(47.2622f, 33.3765f, 45.3083f, 32.4156f, 44.2032f, 32.1273f)
                    curveTo(42.8259f, 31.791f, 40.904f, 31.7109f, 39.3185f, 31.9351f)
                    close()
                }
                path(
                    fill = SolidColor(Color(0xFFA6C8FF)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero
                ) {
                    moveTo(74.8696f, 0.0f)
                    horizontalLineToRelative(7.1304f)
                    verticalLineToRelative(7.1304f)
                    horizontalLineToRelative(-7.1304f)
                    close()
                }
            }
        }
            .build()
        return _iconLogo!!
    }

private var _iconLogo: ImageVector? = null
